project:
  type: book
  output-dir: docs

book:
  title: "Decision Modeling"
  author: "J. Alejandro Gelves"
  date: "12/22/2022"
  chapters:
    - index.qmd
    - Tools.qmd
    - Simulation
    - Tools2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

