project:
  type: book
  output-dir: docs

book:
  title: "Cardano Drep"
  author: "J. Alejandro Gelves"
  date: "09/6/2024"
  cover-image: cardano.png
  chapters:
    - index.qmd
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

