---
format:
  html:
    mermaid:
      theme: neutral
---

# Decisions Under Uncertainty

In this module we will learn how to create decision models. These models rely on probability and expected values. We will map the decision process using a decision tree and value each decision with a monetary value or an expected monetary value (EMV). Our objective is to identify the best decision given the possible choices and uncertainty.

## Shopaholic Retail Company

Imagine you are the CEO of the Shopaholic Retail Company, and you are considering whether to launch a new product line. You have conducted market research and have estimated two possible outcomes based on customer demand and competition.

-   **Success Scenario:** If the new product line is well-received by customers and captures a significant market share, you anticipate an annual profit of \$5 million.
-   **Failure Scenario:** If the new product line fails to gain traction in the market, you estimate an annual loss of \$3 million due to production costs and missed opportunities.

In this decision, you face uncertainty regarding customer preferences, market conditions, and competitive dynamics. The new product line's success or failure will determine your company's financial outcome. Determining how to adequately assess the risks involved in this decision and the potential outcomes is of importance.

## Expected Monetary Value {#sec-EMV}

According to your estimates, you believe that there is a $60$% chance of success and a $40$% chance of failure. Using this information, you can calculate the **expected monetary value (EMV)** of the decision by multiplying the monetary value of each outcome by its respective probability and summing them up:

::: {.pull-right-50 .text-center}
Expected Value = (Prob. of Success \* Value of Success) + (Prob. of Failure \* Value of Failure)

Expected Value = (0.6 \* 5 million) + (0.4 \* -3 million)

Expected Value = 3 million + (-1.2 million)

Expected Value = 1.8 million
:::

\n

The **expected monetary value** estimates the average monetary outcome you can expect from a decision involving uncertainty. In this example, the value is positive, suggesting that launching the new product line results in a profit on average. Mathematically we express the monetary expected value as the sum product of probabilities and monetary values.

::: {.pull-right-50 .text-center}
$EMV=\sum p_{i}x_{i}$
:::

where $EMV$ is the expected monetary value, $p_{i}$ is the probability of outcome $i$, and $x_{i}$ is the monetary value resulting from outcome $i$. Notice that if we had other decisions involving uncertainty, we could also evaluate them using the EMV. Hence, the EMV allows us to rank and choose best decisions when uncertainty is present.

## Decision Trees

**Decision trees** visually map the entire business decision process. Below you can see the decision tree for the decision to introduce a new production line.

```{mermaid}
%%| fig-width: 5
%%| theme: dark
graph LR
    A[ ] -->|Introduce Production Line| C(( )) 
    A[ ] -->|Don't Introduce| B( 0 )
    C -->|Success p=0.6| D( 5 )
    C -->|Failure p=0.4| E( -3 )
```

<br> Decision trees are read from left to right. Notice that there are two main branches stemming from the first decision node (i.e., the first square to the left). You can decide to *Introduce* or *Not Introduce* the new production line. If you *Introduce*, you reach a probability node (i.e., the circle that leads to the success and failure branches) where chance determines success or failure at the probabilities given. In the end, your choice of introducing the new product line yields an expected monetary value of 1.8 million, whereas not introducing the line yields no payoff.

To solve decision trees and find the optimal decision use **backward induction**. Starting from the right of the decision tree and working back to the left at each probability node calculate the EMV. At each decision node, take the maximum of EMV's to identify the optimal decision. Applying this procedure to our simple example, we would start with the probability node that leads to the success and failure branches and calculate the EMV of 1.8 million (refer to @sec-EMV). Moving back to our initial decision, we now have the choice to *Introduce* or *Not Introduce*. In this case we should *Introduce*, since the resulting EMV (1.8) is higher than *Not Introduce* (0).

## Consulting Team

Consider now the option of hiring a consulting team that promises to give you a bit more certainty. The team provides a recommendation based on market research, historical data, and their expertise for \$500,000. However, it is known that the team has a false positive rate (i.e., recommending to go with a project when the project would fail) of 15% and a false negative rate of 5% (i.e., recommending not going with a project and when the project would succeed). Below you can see the updated decision tree with the results of the recommendation (i.e., *Positive*, and *Negative*).

```{mermaid theme=darkly}
%%| fig-width: 5
graph LR
    F(( ))--> |Positive p=?| A[ ]
    A[ ] -->|Introduce Production Line| C(( )) 
    A[ ] -->|Don't Introduce| B( -0.5 )
    C -->|Success p=?| D( 4.5 )
    C -->|Failure p=?| E( -3.5 )
    
    F(( ))--> |Negative p=?| G[ ]
    G[ ] -->|Introduce Production Line| H(( )) 
    G[ ] -->|Don't Introduce| I( -0.5 )
    H -->|Success p=?| J( 4.5 )
    H -->|Failure p=?| K( -3.5 )
```

Note that even though the consultants might recommend not introducing the production line, the CEO can still decide to go against their recommendation. Also, some probabilities are now unknown and must be calculated (they are highlighted in the decision tree with $?$). For example, given that the recommendation is positive, the probability that the introduction would succeed is unknown $p(Success|+)$. We will use probability theory to uncover the missing probabilities in the upcoming sections. Finally, the final payoffs have all been adjusted to reflect the cost of hiring the team of consultants.

Ultimately, we would like gain more certainty on our decision to introduce the production line. Additionally, knowing if we should hire consultants to advise is equally essential.

## Updating Probabilities

The **Law of total probability** is useful in determining the probabilities that we get a positive recommendation $p(+)$ or a negative recommendation $p(-)$. In sum the law states:

::: {.pull-right-50 .text-center}
$p(A)=p(A|B)p(B)+p(A|B^c)p(B^c)$
:::

Substituting the values provided in our problem we obtain:

::: {.pull-right-50 .text-center}
$p(+)=p(+|Failure)p(Failure)+p(+|Success)p(Success)$ \n

$p(+)=0.15(0.4)+0.95(0.6)$ \n

$p(+)=0.63$
:::

Hence, the probability of obtaining a recommendation of introducing the new product line is $63$% and of not recommending the introduction is $p(-)=37$%. The updated decision tree is now:

```{mermaid theme=darkly}
%%| fig-width: 5
graph LR
    F(( ))--> |Positive p=0.63| A[ ]
    A[ ] -->|Introduce Production Line| C(( )) 
    A[ ] -->|Don't Introduce| B( -0.5 )
    C -->|Success p=?| D( 4.5 )
    C -->|Failure p=?| E( -3.5 )
    
    F(( ))--> |Negative p=0.37| G[ ]
    G[ ] -->|Introduce Production Line| H(( )) 
    G[ ] -->|Don't Introduce| I( -0.5 )
    H -->|Success p=?| J( 4.5 )
    H -->|Failure p=?| K( -3.5 )
```

## Bayes' Theorem

Now we can use Bayes' Theorem to update our probabilities given the recommendation from the consulting team. Recall that **Bayes' Theorem** is a concept in probability that helps us update our beliefs when given new information. Mathematically, Bayes' Theorem states:

::: {.pull-right-50 .text-center}
$p(A|B)=\frac{p(B|A)p(A)}{p(B)}$
:::

Substituting values we can find the missing probabilities at the edge of the tree. In particular:

::: {.pull-right-50 .text-center}
$p(Success|+)=\frac{p(+|Success)p(Success)}{p(+)}$ \n

$p(Success|+)=\frac{0.95(0.6)}{0.63}$ \n

$p(Success|+)=0.90$
:::

This implies that $p(Failure|+)=0.10$. Similarly, the probabilities $p(Success|-)$ and $p(Failure|-)$ can be found using Bayes' theorem (the reader should try to obtain these probabilities). The updated decision tree is given below:

```{mermaid theme=darkly}
%%| fig-width: 5
graph LR
    F(( ))--> |Positive p=0.63| A[ ]
    A[ ] -->|Introduce Production Line| C(( )) 
    A[ ] -->|Don't Introduce| B( -0.5 )
    C -->|Success p=0.90| D( 4.5 )
    C -->|Failure p=0.10| E( -3.5 )
    
    F(( ))--> |Negative p=0.37| G[ ]
    G[ ] -->|Introduce Production Line| H(( )) 
    G[ ] -->|Don't Introduce| I( -0.5 )
    H -->|Success p=0.08| J( 4.5 )
    H -->|Failure p=0.92| K( -3.5 )
```

## Optimal Decision {#sec-Optimal}

Now that we have calculated the probabilities we can finally decide whether we should hire the consulting team, and most importantly whether we should introduce the new product line. Summarizing the decision tree by calculating the EMV's for each probability node yields:

```{mermaid theme=darkly}
%%| fig-width: 5
graph LR
    F(( ))--> |Positive p=0.63| A[ ]
    A[ ] -->|Introduce Production Line| C(( ))
    A[ ] -->|Don't Introduce| B( -0.5 )
    C --> D(EMV=3.70)
    
    F(( ))--> |Negative p=0.37| G[ ]
    G[ ] -->|Introduce Production Line| H(( )) 
    G[ ] -->|Don't Introduce| I( -0.5 )
    H --> J(EMV=-2.86)
```

Note that even though the consultants might recommend not introducing the production line, the CEO can still decide to go against their recommendation. If the recommendation is positive, then the EMV resulting from introduction of the product line ($3.70$) is greater than the loss of not introducing the product line ($-0.5$). Similarly, if the recommendation is negative, the EMV from the introduction ($-2.86$) is less than the EMV of not introducing the product line ($-0.5$). As a consequence, the recommendation is aligned with the CEO's best decision.

## The Value of Information

We are now faced with an important question. What is the value of the information provided by the consulting team? In other words, should the CEO hire the consultants? To answer this question, let's start by calculating expected monetary value of the tree in @sec-Optimal:

::: {.pull-right-50 .text-center}
$EMV=0.63(3.70)+0.37(-0.5)$ \n

$EMV=2.146$ \n
:::

This EMV is higher than the EMV of making the decision without the consultants (1.8 million). This highlights that the information provided by the consulting team is valuable to the CEO. Moreover, the CEO should be willing to pay up to \$846,000 (EMV with free information - EMV without information) for the consulting service.

## Readings

The readings for this chapter are mainly from @PMS. Chapter 9 provides an excellent introduction to decision models with a couple of solved problems using Excel. I recommend using R (as a calculator) instead of Excel, as this book mainly uses R. To construct decision trees in R, you can use [mermaid](https://www.rdocumentation.org/packages/DiagrammeR/versions/1.0.10/topics/mermaid) along with [Quarto](https://Quarto.org). Some probability concepts are essential to review before you start reading the chapter. In particular, discrete random variables, expected value, conditional probability, probability rules, and Bayes' theorem.

-   @PMS Chapters 9.1 (Introduction), 9.2 (Elements of Decision Analysis), 9.3 (Single-Stage Decision Problems) and 9.5 (Multistage Decision Problems). It is recommended you follow along in R as opposed to Excel (or Precision Tree Add-In).

-   @JK Chapter 4.1 (Fundamental Probability Concepts), 4.2 (Rules of Probability), 4.3 (Contingency Tables and Probabilities), and 4.4 (The Total Probability Rule and Bayes' Theorem).

-   Quarto: <https://Quarto.org>

-   Mermaid in Quarto Document: <https://quarto.org/docs/authoring/diagrams.html>

-   Mermaid in R Script: <https://www.rdocumentation.org/packages/DiagrammeR/versions/1.0.10/topics/mermaid>

## Lessons Learned In This Chapter

-   Use the concept of Expected Monetary Value to rank decisions involving uncertainty.

-   Use Decision Trees to map the business decision process.

-   Apply backward induction to solve decision problems.

-   Apply the Law of Total Probability and Bayes' Theorem to update probabilities.

-   Determine the price of information.

## Exercises

1. Tesla, a U.S. EV car manufacturer, is considering expanding production to meet potential increases in the demand for one of its cars. Tesla’s alternatives are to construct a new plant, expand the existing plant, or do nothing in the short run. Analysts within Tesla expect the market for their EV’s may expand, remain stable, or contract, with probabilities of 0.35, 0.35, and 0.30, respectively. The table below contains the profit generated under each scenario. What is your recommendation to Tesla?

||Expand|Stable|Contract|
|:-:|:-:|:-:|:-:|
|New Plant|400,000|-100,000|-200,000|
|Expand Plant|250,000|-50,000|-75,000|
|Do Nothing|50,000|0|-30,000|

<details>
  <summary>Suggested Answer</summary>
*We can use expected values to guide our recommendation to Tesla. The expected value of each option is as follows: constructing a new plant is 45,000, expanding plant is 47,500, and doing nothing is 8,500. Following these results we could **recommend Tesla to expand its existing plant**, as this option would give the company the highest expected profit.*
</details>

2. Frontier Airlines is considering purchasing a new airplane from an aircraft manufacturer. The manufacturer offers the airplane for 50 million. The airline estimates that, if the airplane is purchased, it could generate an additional revenue of 120 million over its operational lifetime. However, this is contingent on the condition that the airline industry remains stable and demand for flights remains high, which the airline estimates has a 70% probability of occurring.

    If the industry faces a downturn (a 30% probability), the airline estimates it will only be able to generate $30 million in revenue from the airplane over its lifetime.

    Alternatively, the airline has the option to lease an older model airplane for 10 million. The older airplane would generate $40 million in revenue over its lifetime, regardless of industry conditions.
    
    Should the airline purchase the new airplane or lease the older model?

<details>
  <summary>Suggested Answer</summary>
*Once again we can use the expected value in this problem. The option of buying the airplane yields an expected profit of 43 million dollars, whereas the option of leasing the airplane yields a profit of 30 million. Given this result, we should **recommend Frontier airlines to buy the airplane**.*

</details>

3. PharmaCo is a pharmaceutical company considering whether to launch a new drug called "CureFast". The success of CureFast in the market depends on the drug's effectiveness in treating a particular condition. PharmaCo estimates that there is a 40% chance that the drug will be highly effective and thus successful in the market. If CureFast is successful, the company will earn a profit of 50 million. However, if the drug is not effective, PharmaCo will incur a loss of 20 million due to production, marketing, and other sunk costs.

    Before deciding to launch the drug, PharmaCo can conduct a clinical trial at a cost of $5 million. The clinical trial is not perfect and has the following characteristics:

   - If the drug is truly effective, there is a 90% chance that the clinical trial will show positive results. If the drug is not effective, there is a 15% chance that the clinical trial will still show positive results.

    Should PharmaCo conduct the clinical trial before deciding whether to launch CureFast, and what is the maximum amount they should pay for the trial?

<details>
  <summary>Suggested Answer</summary>
*The expected value when not launching the clinical trial is 8 million. Since the expected value after conducting the trial is higher (11.2 million), **PharmaCo should conduct the clinical trial and use the results to inform their decision on whether to launch CureFast.PharmaCo should pay at most 8.2 million for the clinical trial**.*
</details>

4. João “Golden Toes” Silva is the next Brazilian league wonder kid, and Arsenal's scouts are buzzing with excitement. The club’s analysts estimate that João has a 70% chance of being a success at Arsenal, performing at a top level and helping the club win titles.

    If João is successful, Arsenal stands to make £18 million in profits through merchandise sales, increased ticket revenue, and potential transfer fees. However, if João fails to live up to expectations (which has a 30% chance), it could cost the club £8 million (wasted wages, and negative press).

    Given the risk of signing the player, the club can conduct a thorough physical exam on João to ensure he’s healthy and injury-free (this is an additional test than that required for all signed players). The cost of this physical test is £3 million.

    Based on historical data, if João is a success, there’s a 99% chance that the physical test will show he’s in perfect health. On the other hand, if João is likely to be a flop, there’s still a 5% chance that the test will incorrectly indicate he’s healthy.

    Should Arsenal conduct the physical test? Would your recommendation change if the price of the test could be bargained down?
    
<details>
  <summary>Suggested Answer</summary>
*Without the test, the expected value is 10,200,000. With the test, the expected value is 9,354,000. We **recommend Arsenal go without the test and sign the player**. If the club can decrease the price of the test to at most 2,154,000 they should perform the test and proceed with the signing of João, if the test indicates that he is healthy.*
</details>

5. The Crypto Gains investment firm is planning to invest in Bitcoin to diversify its portfolio. The firm knows that it will need 50 Bitcoins six months from now to meet its investment strategy. The company has three options for acquiring the needed Bitcoins. It can buy the Bitcoins at the market price six months from now or purchase a futures contract now. The contract guarantees delivery of the Bitcoins in six months, and the cost of purchasing it will be based on today’s market price. Assume that the possible Bitcoin futures contracts available for purchase are for 25 Bitcoins or 50 Bitcoins only. No futures contracts can be purchased or sold in the intervening months; thus, Crypto Gains' possible decisions are to:

- Purchase a futures contract for 50 Bitcoins now.
- Purchase a futures contract for 25 Bitcoins now and purchase 25     Bitcoins in six months at market price.
- Purchase all 50 Bitcoins needed in six months at the market price.

The price of Bitcoin bought now for delivery in six months is 30,000 dollars per Bitcoin. The transaction cost for 25-Bitcoin and 50-Bitcoin future contracts are 1,500 and 2,800 dollars, respectively. Finally, the company has assessed the probability distribution for the possible Bitcoin prices six months from now in dollars per Bitcoin. The table contains the possible prices and the corresponding probabilities.

|Price|	Probability|
|:---:|:----------:|
|$28,000|	0.10|
|$29,500|	0.30|
|$31,000|	0.35|
|$32,500|	0.15|
|$34,000|	0.10|

Which investment strategy should Crypto Gains pursue to minimize risk and potential costs while securing the necessary Bitcoins? How robust is the decision to changes in the future contracts price?

<details>
  <summary>Suggested Answer</summary>
*The expected values are a follows: buy 50 Bitcoins now via futures contract: 1,502,800, buy 25 Bitcoins now via futures contract, and 25 Bitcoins in six months at market price: 1,520,875, buy all 50 Bitcoins in six months at market price: $1,538,750.
The lowest expected cost is from the first option—purchasing a futures contract for 50 Bitcoins now. This option provides the certainty of price, avoiding the risk of price fluctuations in the market, and results in the lowest overall cost, $1,502,800.
**Crypto Gains should purchase a futures contract for 50 Bitcoins now to secure the necessary investment and minimize costs**.*
</details>