# Tools for Working With Simulation

Business simulation is a type of computer-based modeling that allows us to experiment and analyze different business scenarios and strategies. It is a cost-effective way to explore and test business decisions in production, marketing, finance, and operations, among many other business areas. 

We will be using R to conduct business simulation. But before we jump into building our simulation models, we need to learn the tools that allow us to perform this analysis. In this module, we will introduce the building blocks of our computer simulation models. In the next module, we will apply these tools to business problems.

## R Basics

Objects, vectors and data frames are all important in the R programming language. They mainly help us store and manipulate data. An **object** is a piece of data that can be stored in a variable. It can be as simple as a single integer or letter. **Vectors** are one-dimensional arrays of data. Vectors can contain elements of various data types, such as numerical values, character strings, and logical values (i.e., TRUE or FALSE). However, every component of the vector must be the same data type. Lastly, a **data frame**, is a two-dimensional data table with rows and columns. Each column in a data frame represents a different variable, and each row represents a single observation or record.

## R Intermediate

Loops and conditionals

random number generators
