<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Decision Modeling - 1&nbsp; Decisions Under Uncertainty</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Tools.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Decisions.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Decisions Under Uncertainty</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Decision Modeling</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Decisions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Decisions Under Uncertainty</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tools for Working With Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Tools2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Time Series Tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Model Benchmarks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ETS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ETS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ARIMA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ARIMA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#shopaholic-retail-company" id="toc-shopaholic-retail-company" class="nav-link active" data-scroll-target="#shopaholic-retail-company"><span class="header-section-number">1.1</span> Shopaholic Retail Company</a></li>
  <li><a href="#sec-EMV" id="toc-sec-EMV" class="nav-link" data-scroll-target="#sec-EMV"><span class="header-section-number">1.2</span> Expected Monetary Value</a></li>
  <li><a href="#decision-trees" id="toc-decision-trees" class="nav-link" data-scroll-target="#decision-trees"><span class="header-section-number">1.3</span> Decision Trees</a></li>
  <li><a href="#consulting-team" id="toc-consulting-team" class="nav-link" data-scroll-target="#consulting-team"><span class="header-section-number">1.4</span> Consulting Team</a></li>
  <li><a href="#updating-probabilities" id="toc-updating-probabilities" class="nav-link" data-scroll-target="#updating-probabilities"><span class="header-section-number">1.5</span> Updating Probabilities</a></li>
  <li><a href="#bayes-theorem" id="toc-bayes-theorem" class="nav-link" data-scroll-target="#bayes-theorem"><span class="header-section-number">1.6</span> Bayes’ Theorem</a></li>
  <li><a href="#sec-Optimal" id="toc-sec-Optimal" class="nav-link" data-scroll-target="#sec-Optimal"><span class="header-section-number">1.7</span> Optimal Decision</a></li>
  <li><a href="#the-value-of-information" id="toc-the-value-of-information" class="nav-link" data-scroll-target="#the-value-of-information"><span class="header-section-number">1.8</span> The Value of Information</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings"><span class="header-section-number">1.9</span> Readings</a></li>
  <li><a href="#lessons-learned-in-this-chapter" id="toc-lessons-learned-in-this-chapter" class="nav-link" data-scroll-target="#lessons-learned-in-this-chapter"><span class="header-section-number">1.10</span> Lessons Learned In This Chapter</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">1.11</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Decisions Under Uncertainty</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this module we will learn how to create decision models. These models rely on probability and expected values. We will map the decision process using a decision tree and value each decision with a monetary value or an expected monetary value (EMV). Our objective is to identify the best decision given the possible choices and uncertainty.</p>
<section id="shopaholic-retail-company" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="shopaholic-retail-company"><span class="header-section-number">1.1</span> Shopaholic Retail Company</h2>
<p>Imagine you are the CEO of the Shopaholic Retail Company, and you are considering whether to launch a new product line. You have conducted market research and have estimated two possible outcomes based on customer demand and competition.</p>
<ul>
<li><strong>Success Scenario:</strong> If the new product line is well-received by customers and captures a significant market share, you anticipate an annual profit of $5 million.</li>
<li><strong>Failure Scenario:</strong> If the new product line fails to gain traction in the market, you estimate an annual loss of $3 million due to production costs and missed opportunities.</li>
</ul>
<p>In this decision, you face uncertainty regarding customer preferences, market conditions, and competitive dynamics. The new product line’s success or failure will determine your company’s financial outcome. Determining how to adequately assess the risks involved in this decision and the potential outcomes is of importance.</p>
</section>
<section id="sec-EMV" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-EMV"><span class="header-section-number">1.2</span> Expected Monetary Value</h2>
<p>According to your estimates, you believe that there is a <span class="math inline">\(60\)</span>% chance of success and a <span class="math inline">\(40\)</span>% chance of failure. Using this information, you can calculate the <strong>expected monetary value (EMV)</strong> of the decision by multiplying the monetary value of each outcome by its respective probability and summing them up:</p>
<div class="pull-right-50 text-center">
<p>Expected Value = (Prob. of Success * Value of Success) + (Prob. of Failure * Value of Failure)</p>
<p>Expected Value = (0.6 * 5 million) + (0.4 * -3 million)</p>
<p>Expected Value = 3 million + (-1.2 million)</p>
<p>Expected Value = 1.8 million</p>
</div>
<p>The <strong>expected monetary value</strong> estimates the average monetary outcome you can expect from a decision involving uncertainty. In this example, the value is positive, suggesting that launching the new product line results in a profit on average. Mathematically we express the monetary expected value as the sum product of probabilities and monetary values.</p>
<div class="pull-right-50 text-center">
<p><span class="math inline">\(EMV=\sum p_{i}x_{i}\)</span></p>
</div>
<p>where <span class="math inline">\(EMV\)</span> is the expected monetary value, <span class="math inline">\(p_{i}\)</span> is the probability of outcome <span class="math inline">\(i\)</span>, and <span class="math inline">\(x_{i}\)</span> is the monetary value resulting from outcome <span class="math inline">\(i\)</span>. Notice that if we had other decisions involving uncertainty, we could also evaluate them using the EMV. Hence, the EMV allows us to rank and choose best decisions when uncertainty is present.</p>
</section>
<section id="decision-trees" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="decision-trees"><span class="header-section-number">1.3</span> Decision Trees</h2>
<p><strong>Decision trees</strong> visually map the entire business decision process. Below you can see the decision tree for the decision to introduce a new production line.</p>
<div class="cell" data-fig-width="5" data-theme="dark" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A[ ] --&gt;|Introduce Production Line| C(( )) 
    A[ ] --&gt;|Don't Introduce| B( 0 )
    C --&gt;|Success p=0.6| D( 5 )
    C --&gt;|Failure p=0.4| E( -3 )
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><br> Decision trees are read from left to right. Notice that there are two main branches stemming from the first decision node (i.e., the first square to the left). You can decide to <em>Introduce</em> or <em>Not Introduce</em> the new production line. If you <em>Introduce</em>, you reach a probability node (i.e., the circle that leads to the success and failure branches) where chance determines success or failure at the probabilities given. In the end, your choice of introducing the new product line yields an expected monetary value of 1.8 million, whereas not introducing the line yields no payoff.</p>
<p>To solve decision trees and find the optimal decision use <strong>backward induction</strong>. Starting from the right of the decision tree and working back to the left at each probability node calculate the EMV. At each decision node, take the maximum of EMV’s to identify the optimal decision. Applying this procedure to our simple example, we would start with the probability node that leads to the success and failure branches and calculate the EMV of 1.8 million (refer to <a href="#sec-EMV" class="quarto-xref"><span>Section 1.2</span></a>). Moving back to our initial decision, we now have the choice to <em>Introduce</em> or <em>Not Introduce</em>. In this case we should <em>Introduce</em>, since the resulting EMV (1.8) is higher than <em>Not Introduce</em> (0).</p>
</section>
<section id="consulting-team" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="consulting-team"><span class="header-section-number">1.4</span> Consulting Team</h2>
<p>Consider now the option of hiring a consulting team that promises to give you a bit more certainty. The team provides a recommendation based on market research, historical data, and their expertise for $500,000. However, it is known that the team has a false positive rate (i.e., recommending to go with a project when the project would fail) of 15% and a false negative rate of 5% (i.e., recommending not going with a project and when the project would succeed). Below you can see the updated decision tree with the results of the recommendation (i.e., <em>Positive</em>, and <em>Negative</em>).</p>
<div class="cell" data-fig-width="5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    F(( ))--&gt; |Positive p=?| A[ ]
    A[ ] --&gt;|Introduce Production Line| C(( )) 
    A[ ] --&gt;|Don't Introduce| B( -0.5 )
    C --&gt;|Success p=?| D( 4.5 )
    C --&gt;|Failure p=?| E( -3.5 )
    
    F(( ))--&gt; |Negative p=?| G[ ]
    G[ ] --&gt;|Introduce Production Line| H(( )) 
    G[ ] --&gt;|Don't Introduce| I( -0.5 )
    H --&gt;|Success p=?| J( 4.5 )
    H --&gt;|Failure p=?| K( -3.5 )
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Note that even though the consultants might recommend not introducing the production line, the CEO can still decide to go against their recommendation. Also, some probabilities are now unknown and must be calculated (they are highlighted in the decision tree with <span class="math inline">\(?\)</span>). For example, given that the recommendation is positive, the probability that the introduction would succeed is unknown <span class="math inline">\(p(Success|+)\)</span>. We will use probability theory to uncover the missing probabilities in the upcoming sections. Finally, the final payoffs have all been adjusted to reflect the cost of hiring the team of consultants.</p>
<p>Ultimately, we would like gain more certainty on our decision to introduce the production line. Additionally, knowing if we should hire consultants to advise is equally essential.</p>
</section>
<section id="updating-probabilities" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="updating-probabilities"><span class="header-section-number">1.5</span> Updating Probabilities</h2>
<p>The <strong>Law of total probability</strong> is useful in determining the probabilities that we get a positive recommendation <span class="math inline">\(p(+)\)</span> or a negative recommendation <span class="math inline">\(p(-)\)</span>. In sum the law states:</p>
<div class="pull-right-50 text-center">
<p><span class="math inline">\(p(A)=p(A|B)p(B)+p(A|B^c)p(B^c)\)</span></p>
</div>
<p>Substituting the values provided in our problem we obtain:</p>
<div class="pull-right-50 text-center">
<p><span class="math inline">\(p(+)=p(+|Failure)p(Failure)+p(+|Success)p(Success)\)</span> </p>
<p><span class="math inline">\(p(+)=0.15(0.4)+0.95(0.6)\)</span> </p>
<p><span class="math inline">\(p(+)=0.63\)</span></p>
</div>
<p>Hence, the probability of obtaining a recommendation of introducing the new product line is <span class="math inline">\(63\)</span>% and of not recommending the introduction is <span class="math inline">\(p(-)=37\)</span>%. The updated decision tree is now:</p>
<div class="cell" data-fig-width="5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    F(( ))--&gt; |Positive p=0.63| A[ ]
    A[ ] --&gt;|Introduce Production Line| C(( )) 
    A[ ] --&gt;|Don't Introduce| B( -0.5 )
    C --&gt;|Success p=?| D( 4.5 )
    C --&gt;|Failure p=?| E( -3.5 )
    
    F(( ))--&gt; |Negative p=0.37| G[ ]
    G[ ] --&gt;|Introduce Production Line| H(( )) 
    G[ ] --&gt;|Don't Introduce| I( -0.5 )
    H --&gt;|Success p=?| J( 4.5 )
    H --&gt;|Failure p=?| K( -3.5 )
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="bayes-theorem" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="bayes-theorem"><span class="header-section-number">1.6</span> Bayes’ Theorem</h2>
<p>Now we can use Bayes’ Theorem to update our probabilities given the recommendation from the consulting team. Recall that <strong>Bayes’ Theorem</strong> is a concept in probability that helps us update our beliefs when given new information. Mathematically, Bayes’ Theorem states:</p>
<div class="pull-right-50 text-center">
<p><span class="math inline">\(p(A|B)=\frac{p(B|A)p(A)}{p(B)}\)</span></p>
</div>
<p>Substituting values we can find the missing probabilities at the edge of the tree. In particular:</p>
<div class="pull-right-50 text-center">
<p><span class="math inline">\(p(Success|+)=\frac{p(+|Success)p(Success)}{p(+)}\)</span> </p>
<p><span class="math inline">\(p(Success|+)=\frac{0.95(0.6)}{0.63}\)</span> </p>
<p><span class="math inline">\(p(Success|+)=0.90\)</span></p>
</div>
<p>This implies that <span class="math inline">\(p(Failure|+)=0.10\)</span>. Similarly, the probabilities <span class="math inline">\(p(Success|-)\)</span> and <span class="math inline">\(p(Failure|-)\)</span> can be found using Bayes’ theorem (the reader should try to obtain these probabilities). The updated decision tree is given below:</p>
<div class="cell" data-fig-width="5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    F(( ))--&gt; |Positive p=0.63| A[ ]
    A[ ] --&gt;|Introduce Production Line| C(( )) 
    A[ ] --&gt;|Don't Introduce| B( -0.5 )
    C --&gt;|Success p=0.90| D( 4.5 )
    C --&gt;|Failure p=0.10| E( -3.5 )
    
    F(( ))--&gt; |Negative p=0.37| G[ ]
    G[ ] --&gt;|Introduce Production Line| H(( )) 
    G[ ] --&gt;|Don't Introduce| I( -0.5 )
    H --&gt;|Success p=0.08| J( 4.5 )
    H --&gt;|Failure p=0.92| K( -3.5 )
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="sec-Optimal" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="sec-Optimal"><span class="header-section-number">1.7</span> Optimal Decision</h2>
<p>Now that we have calculated the probabilities we can finally decide whether we should hire the consulting team, and most importantly whether we should introduce the new product line. Summarizing the decision tree by calculating the EMV’s for each probability node yields:</p>
<div class="cell" data-fig-width="5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    F(( ))--&gt; |Positive p=0.63| A[ ]
    A[ ] --&gt;|Introduce Production Line| C(( ))
    A[ ] --&gt;|Don't Introduce| B( -0.5 )
    C --&gt; D(EMV=3.70)
    
    F(( ))--&gt; |Negative p=0.37| G[ ]
    G[ ] --&gt;|Introduce Production Line| H(( )) 
    G[ ] --&gt;|Don't Introduce| I( -0.5 )
    H --&gt; J(EMV=-2.86)
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Note that even though the consultants might recommend not introducing the production line, the CEO can still decide to go against their recommendation. If the recommendation is positive, then the EMV resulting from introduction of the product line (<span class="math inline">\(3.70\)</span>) is greater than the loss of not introducing the product line (<span class="math inline">\(-0.5\)</span>). Similarly, if the recommendation is negative, the EMV from the introduction (<span class="math inline">\(-2.86\)</span>) is less than the EMV of not introducing the product line (<span class="math inline">\(-0.5\)</span>). As a consequence, the recommendation is aligned with the CEO’s best decision.</p>
</section>
<section id="the-value-of-information" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="the-value-of-information"><span class="header-section-number">1.8</span> The Value of Information</h2>
<p>We are now faced with an important question. What is the value of the information provided by the consulting team? In other words, should the CEO hire the consultants? To answer this question, let’s start by calculating expected monetary value of the tree in <a href="#sec-Optimal" class="quarto-xref"><span>Section 1.7</span></a>:</p>
<div class="pull-right-50 text-center">
<p><span class="math inline">\(EMV=0.63(3.70)+0.37(-0.5)\)</span> </p>
<p><span class="math inline">\(EMV=2.146\)</span> </p>
</div>
<p>This EMV is higher than the EMV of making the decision without the consultants (1.8 million). This highlights that the information provided by the consulting team is valuable to the CEO. Moreover, the CEO should be willing to pay up to $846,000 (EMV with free information - EMV without information) for the consulting service.</p>
</section>
<section id="readings" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="readings"><span class="header-section-number">1.9</span> Readings</h2>
<p>The readings for this chapter are mainly from <span class="citation" data-cites="PMS">Winston and Albright (<a href="references.html#ref-PMS" role="doc-biblioref">2019</a>)</span>. Chapter 9 provides an excellent introduction to decision models with a couple of solved problems using Excel. I recommend using R (as a calculator) instead of Excel, as this book mainly uses R. To construct decision trees in R, you can use <a href="https://www.rdocumentation.org/packages/DiagrammeR/versions/1.0.10/topics/mermaid">mermaid</a> along with <a href="https://Quarto.org">Quarto</a>. Some probability concepts are essential to review before you start reading the chapter. In particular, discrete random variables, expected value, conditional probability, probability rules, and Bayes’ theorem.</p>
<ul>
<li><p><span class="citation" data-cites="PMS">Winston and Albright (<a href="references.html#ref-PMS" role="doc-biblioref">2019</a>)</span> Chapters 9.1 (Introduction), 9.2 (Elements of Decision Analysis), 9.3 (Single-Stage Decision Problems) and 9.5 (Multistage Decision Problems). It is recommended you follow along in R as opposed to Excel (or Precision Tree Add-In).</p></li>
<li><p><span class="citation" data-cites="JK">Jaggia and Kelly (<a href="references.html#ref-JK" role="doc-biblioref">2022</a>)</span> Chapter 4.1 (Fundamental Probability Concepts), 4.2 (Rules of Probability), 4.3 (Contingency Tables and Probabilities), and 4.4 (The Total Probability Rule and Bayes’ Theorem).</p></li>
<li><p>Quarto: <a href="https://Quarto.org" class="uri">https://Quarto.org</a></p></li>
<li><p>Mermaid in Quarto Document: <a href="https://quarto.org/docs/authoring/diagrams.html" class="uri">https://quarto.org/docs/authoring/diagrams.html</a></p></li>
<li><p>Mermaid in R Script: <a href="https://www.rdocumentation.org/packages/DiagrammeR/versions/1.0.10/topics/mermaid" class="uri">https://www.rdocumentation.org/packages/DiagrammeR/versions/1.0.10/topics/mermaid</a></p></li>
</ul>
</section>
<section id="lessons-learned-in-this-chapter" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="lessons-learned-in-this-chapter"><span class="header-section-number">1.10</span> Lessons Learned In This Chapter</h2>
<ul>
<li><p>Use the concept of Expected Monetary Value to rank decisions involving uncertainty.</p></li>
<li><p>Use Decision Trees to map the business decision process.</p></li>
<li><p>Apply backward induction to solve decision problems.</p></li>
<li><p>Apply the Law of Total Probability and Bayes’ Theorem to update probabilities.</p></li>
<li><p>Determine the price of information.</p></li>
</ul>
</section>
<section id="exercises" class="level2" data-number="1.11">
<h2 data-number="1.11" class="anchored" data-anchor-id="exercises"><span class="header-section-number">1.11</span> Exercises</h2>
<ol type="1">
<li>Tesla, a U.S. EV car manufacturer, is considering expanding production to meet potential increases in the demand for one of its cars. Tesla’s alternatives are to construct a new plant, expand the existing plant, or do nothing in the short run. Analysts within Tesla expect the market for their EV’s may expand, remain stable, or contract, with probabilities of 0.35, 0.35, and 0.30, respectively. The table below contains the profit generated under each scenario. What is your recommendation to Tesla?</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Expand</th>
<th style="text-align: center;">Stable</th>
<th style="text-align: center;">Contract</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">New Plant</td>
<td style="text-align: center;">400,000</td>
<td style="text-align: center;">-100,000</td>
<td style="text-align: center;">-200,000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Expand Plant</td>
<td style="text-align: center;">250,000</td>
<td style="text-align: center;">-50,000</td>
<td style="text-align: center;">-75,000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Do Nothing</td>
<td style="text-align: center;">50,000</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">-30,000</td>
</tr>
</tbody>
</table>
<details>
<summary>
Suggested Answer
</summary>
<em>We can use expected values to guide our recommendation to Tesla. The expected value of each option is as follows: constructing a new plant is 45,000, expanding plant is 47,500, and doing nothing is 8,500. Following these results we could <strong>recommend Tesla to expand its existing plant</strong>, as this option would give the company the highest expected profit.</em>
</details>
<ol start="2" type="1">
<li><p>Frontier Airlines is considering purchasing a new airplane from an aircraft manufacturer. The manufacturer offers the airplane for 50 million. The airline estimates that, if the airplane is purchased, it could generate an additional revenue of 120 million over its operational lifetime. However, this is contingent on the condition that the airline industry remains stable and demand for flights remains high, which the airline estimates has a 70% probability of occurring.</p>
<p>If the industry faces a downturn (a 30% probability), the airline estimates it will only be able to generate $30 million in revenue from the airplane over its lifetime.</p>
<p>Alternatively, the airline has the option to lease an older model airplane for 10 million. The older airplane would generate $40 million in revenue over its lifetime, regardless of industry conditions.</p>
<p>Should the airline purchase the new airplane or lease the older model?</p></li>
</ol>
<details>
<summary>
Suggested Answer
</summary>
<p><em>Once again we can use the expected value in this problem. The option of buying the airplane yields an expected profit of 43 million dollars, whereas the option of leasing the airplane yields a profit of 30 million. Given this result, we should <strong>recommend Frontier airlines to buy the airplane</strong>.</em></p>
</details>
<ol start="3" type="1">
<li><p>PharmaCo is a pharmaceutical company considering whether to launch a new drug called “CureFast”. The success of CureFast in the market depends on the drug’s effectiveness in treating a particular condition. PharmaCo estimates that there is a 40% chance that the drug will be highly effective and thus successful in the market. If CureFast is successful, the company will earn a profit of 50 million. However, if the drug is not effective, PharmaCo will incur a loss of 20 million due to production, marketing, and other sunk costs.</p>
<p>Before deciding to launch the drug, PharmaCo can conduct a clinical trial at a cost of $5 million. The clinical trial is not perfect and has the following characteristics:</p>
<ul>
<li>If the drug is truly effective, there is a 90% chance that the clinical trial will show positive results. If the drug is not effective, there is a 15% chance that the clinical trial will still show positive results.</li>
</ul>
<p>Should PharmaCo conduct the clinical trial before deciding whether to launch CureFast, and what is the maximum amount they should pay for the trial?</p></li>
</ol>
<details>
<summary>
Suggested Answer
</summary>
<em>The expected value when not launching the clinical trial is 8 million. Since the expected value after conducting the trial is higher (11.2 million), <strong>PharmaCo should conduct the clinical trial and use the results to inform their decision on whether to launch CureFast.PharmaCo should pay at most 8.2 million for the clinical trial</strong>.</em>
</details>
<ol start="4" type="1">
<li><p>João “Golden Toes” Silva is the next Brazilian league wonder kid, and Arsenal’s scouts are buzzing with excitement. The club’s analysts estimate that João has a 70% chance of being a success at Arsenal, performing at a top level and helping the club win titles.</p>
<p>If João is successful, Arsenal stands to make £18 million in profits through merchandise sales, increased ticket revenue, and potential transfer fees. However, if João fails to live up to expectations (which has a 30% chance), it could cost the club £8 million (wasted wages, and negative press).</p>
<p>Given the risk of signing the player, the club can conduct a thorough physical exam on João to ensure he’s healthy and injury-free. The cost of this physical test is £3 million.</p>
<p>Based on historical data, if João is a success, there’s a 99% chance that the physical test will show he’s in perfect health. On the other hand, if João is likely to be a flop, there’s still a 5% chance that the test will incorrectly indicate he’s healthy.</p>
<p>Should Arsenal conduct the physical test and then decide whether to sign João “Golden Toes” Silva, or should they take a chance and sign him without the test? Should they try to find ways to lower the price of the test?</p></li>
</ol>
<details>
<summary>
Suggested Answer
</summary>
<em>Without the test, the expected value is 10,200,000. With the test the expected value is 9,350,000. We would <strong>recommend Arsenal to go without the test and sign the player</strong>. If the club can decrease the value of the test, then it should</em>
</details>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-JK" class="csl-entry" role="listitem">
Jaggia, Sanjiv, and Allison Kelly. 2022. <em>Business Statistics</em>. McGraw Hill.
</div>
<div id="ref-PMS" class="csl-entry" role="listitem">
Winston, Wayne, and Christian Albright. 2019. <em>Practical Management Science</em>. Cengage.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Tools.html" class="pagination-link" aria-label="Tools for Working With Simulation">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tools for Working With Simulation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>